const elements = {
  "H": {
    "name": "Hydrogen",
    "number": 1,
    "mass": "1.008",
    "description": "Hydrogen is element number 1 with atomic mass 1.008.",
    "category": "Nonmetal",
    "appearance": "Colorless gas",
    "electronConfiguration": "1s¹",
    "discovery": "Henry Cavendish (1766)",
    "occurrence": "Found in water and most organic compounds",
    "uses": "Used in rocket fuel, ammonia production, hydrogenation",
    "model": "Atomic Model: [H] - 1 electron",
    "isToxic": false,
    "stateAtRoomTemp": "Gas",
    "safetyPrecautions": "Keep away from flames, sparks, and static electricity. Use only in well-ventilated areas. Store in approved gas cylinders; check for leaks with soapy water. Install flame arrestors in experimental setups. Wear goggles, gloves, and lab coats. Avoid using in confined or enclosed spaces. Don't exceed pressure limits; use regulators and check valves."
  },
  "He": {
    "name": "Helium",
    "number": 2,
    "mass": "4.0026",
    "description": "Helium is element number 2 with atomic mass 4.0026.",
    "category": "Noble Gas",
    "appearance": "Colorless, odorless gas",
    "electronConfiguration": "1s²",
    "discovery": "Janssen & Lockyer (1868)",
    "occurrence": "Extracted from natural gas deposits",
    "uses": "Used in balloons, cryogenics, gas chromatography",
    "model": "Atomic Model: [He] - 2 electrons",
    "isToxic": false,
    "stateAtRoomTemp": "Gas",
    "safetyPrecautions": "Non-toxic and inert, but can cause asphyxiation in confined spaces"
  },
  "Li": {
    "name": "Lithium",
    "number": 3,
    "mass": "6.94",
    "description": "Lithium is element number 3 with atomic mass 6.94.",
    "category": "Alkali Metal",
    "appearance": "Soft, silvery-white metal",
    "electronConfiguration": "[He] 2s¹",
    "discovery": "Johan August Arfwedson (1817)",
    "occurrence": "Found in minerals and brines",
    "uses": "Batteries, psychiatric medications, nuclear fusion",
    "model": "Atomic Model: [Li] - 3 electrons",
    "isToxic": true,
    "stateAtRoomTemp": "Solid",
    "safetyPrecautions": "Highly reactive with water, store under mineral oil or in inert atmosphere"
  },
  "Be": {
    "name": "Beryllium",
    "number": 4,
    "mass": "9.0122",
    "description": "Beryllium is element number 4 with atomic mass 9.0122.",
    "category": "Alkaline Earth Metal",
    "appearance": "Beryllium appears in a characteristic physical form typical to alkaline earth metals.",
    "electronConfiguration": "[He] 2s²",
    "discovery": "The discovery of Beryllium dates back to historical or modern scientific research.",
    "occurrence": "Beryllium is found in nature or synthesized in laboratories.",
    "uses": "Beryllium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Be] - 4 electrons"
  },
  "B": {
    "name": "Boron",
    "number": 5,
    "mass": "10.81",
    "description": "Boron is element number 5 with atomic mass 10.81.",
    "category": "Metalloid",
    "appearance": "Boron appears in a characteristic physical form typical to metalloids.",
    "electronConfiguration": "[He] 2s² 2p¹",
    "discovery": "The discovery of Boron dates back to historical or modern scientific research.",
    "occurrence": "Boron is found in nature or synthesized in laboratories.",
    "uses": "Boron is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [B] - 5 electrons"
  },
  "C": {
    "name": "Carbon",
    "number": 6,
    "mass": "12.011",
    "description": "Carbon is element number 6 with atomic mass 12.011.",
    "category": "Nonmetal",
    "appearance": "Diamond, graphite, amorphous black",
    "electronConfiguration": "[He] 2s² 2p²",
    "discovery": "Ancient times",
    "occurrence": "In coal, oil, gas, limestone, living things",
    "uses": "Steel manufacturing, graphite, organic chemistry",
    "model": "Atomic Model: [C] - 6 electrons"
  },
  "N": {
    "name": "Nitrogen",
    "number": 7,
    "mass": "14.007",
    "description": "Nitrogen is element number 7 with atomic mass 14.007.",
    "category": "Nonmetal",
    "appearance": "Nitrogen appears in a characteristic physical form typical to nonmetals.",
    "electronConfiguration": "[He] 2s² 2p³",
    "discovery": "The discovery of Nitrogen dates back to historical or modern scientific research.",
    "occurrence": "Nitrogen is found in nature or synthesized in laboratories.",
    "uses": "Nitrogen is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [N] - 7 electrons"
  },
  "O": {
    "name": "Oxygen",
    "number": 8,
    "mass": "15.999",
    "description": "Oxygen is element number 8 with atomic mass 15.999.",
    "category": "Nonmetal",
    "appearance": "Colorless gas",
    "electronConfiguration": "[He] 2s² 2p⁴",
    "discovery": "Carl Wilhelm Scheele (1772)",
    "occurrence": "Air (21%), water, oxides",
    "uses": "Respiration, combustion, steelmaking",
    "model": "Atomic Model: [O] - 8 electrons"
  },
  "F": {
    "name": "Fluorine",
    "number": 9,
    "mass": "18.998",
    "description": "Fluorine is element number 9 with atomic mass 18.998.",
    "category": "Halogen",
    "appearance": "Fluorine appears in a characteristic physical form typical to halogens.",
    "electronConfiguration": "[He] 2s² 2p⁵",
    "discovery": "The discovery of Fluorine dates back to historical or modern scientific research.",
    "occurrence": "Fluorine is found in nature or synthesized in laboratories.",
    "uses": "Fluorine is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [F] - 9 electrons"
  },
  "Ne": {
    "name": "Neon",
    "number": 10,
    "mass": "20.180",
    "description": "Neon is element number 10 with atomic mass 20.180.",
    "category": "Noble Gas",
    "appearance": "Neon appears in a characteristic physical form typical to noble gass.",
    "electronConfiguration": "[He] 2s² 2p⁶",
    "discovery": "The discovery of Neon dates back to historical or modern scientific research.",
    "occurrence": "Neon is found in nature or synthesized in laboratories.",
    "uses": "Neon is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Ne] - 10 electrons"
  },
  "Na": {
    "name": "Sodium",
    "number": 11,
    "mass": "22.990",
    "description": "Sodium is element number 11 with atomic mass 22.990.",
    "category": "Alkali Metal",
    "appearance": "Sodium appears in a characteristic physical form typical to alkali metals.",
    "electronConfiguration": "[Ne] 3s¹",
    "discovery": "The discovery of Sodium dates back to historical or modern scientific research.",
    "occurrence": "Sodium is found in nature or synthesized in laboratories.",
    "uses": "Sodium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Na] - 11 electrons"
  },
  "Mg": {
    "name": "Magnesium",
    "number": 12,
    "mass": "24.305",
    "description": "Magnesium is element number 12 with atomic mass 24.305.",
    "category": "Alkaline Earth Metal",
    "appearance": "Magnesium appears in a characteristic physical form typical to alkaline earth metals.",
    "electronConfiguration": "[Ne] 3s²",
    "discovery": "The discovery of Magnesium dates back to historical or modern scientific research.",
    "occurrence": "Magnesium is found in nature or synthesized in laboratories.",
    "uses": "Magnesium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Mg] - 12 electrons"
  },
  "Al": {
    "name": "Aluminium",
    "number": 13,
    "mass": "26.982",
    "description": "Aluminium is element number 13 with atomic mass 26.982.",
    "category": "Post-Transition Metal",
    "appearance": "Aluminium appears in a characteristic physical form typical to post-transition metals.",
    "electronConfiguration": "[Ne] 3s\u00b2 3p\u00b9",
    "discovery": "The discovery of Aluminium dates back to historical or modern scientific research.",
    "occurrence": "Aluminium is found in nature or synthesized in laboratories.",
    "uses": "Aluminium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Al] - 13 electrons"
  },
  "Si": {
    "name": "Silicon",
    "number": 14,
    "mass": "28.085",
    "description": "Silicon is element number 14 with atomic mass 28.085.",
    "category": "Metalloid",
    "appearance": "Silicon appears in a characteristic physical form typical to metalloids.",
    "electronConfiguration": "[Ne] 3s\u00b2 3p\u00b2",
    "discovery": "The discovery of Silicon dates back to historical or modern scientific research.",
    "occurrence": "Silicon is found in nature or synthesized in laboratories.",
    "uses": "Silicon is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Si] - 14 electrons"
  },
  "P": {
    "name": "Phosphorus",
    "number": 15,
    "mass": "30.974",
    "description": "Phosphorus is element number 15 with atomic mass 30.974.",
    "category": "Nonmetal",
    "appearance": "Phosphorus appears in a characteristic physical form typical to nonmetals.",
    "electronConfiguration": "[Ne] 3s\u00b2 3p\u00b3",
    "discovery": "The discovery of Phosphorus dates back to historical or modern scientific research.",
    "occurrence": "Phosphorus is found in nature or synthesized in laboratories.",
    "uses": "Phosphorus is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [P] - 15 electrons"
  },
  "S": {
    "name": "Sulfur",
    "number": 16,
    "mass": "32.06",
    "description": "Sulfur is element number 16 with atomic mass 32.06.",
    "category": "Nonmetal",
    "appearance": "Sulfur appears in a characteristic physical form typical to nonmetals.",
    "electronConfiguration": "[Ne] 3s\u00b2 3p\u2074",
    "discovery": "The discovery of Sulfur dates back to historical or modern scientific research.",
    "occurrence": "Sulfur is found in nature or synthesized in laboratories.",
    "uses": "Sulfur is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [S] - 16 electrons"
  },
  "Cl": {
    "name": "Chlorine",
    "number": 17,
    "mass": "35.45",
    "description": "Chlorine is element number 17 with atomic mass 35.45.",
    "category": "Halogen",
    "appearance": "Chlorine appears in a characteristic physical form typical to halogens.",
    "electronConfiguration": "[Ne] 3s\u00b2 3p\u2075",
    "discovery": "The discovery of Chlorine dates back to historical or modern scientific research.",
    "occurrence": "Chlorine is found in nature or synthesized in laboratories.",
    "uses": "Chlorine is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Cl] - 17 electrons"
  },
  "Ar": {
    "name": "Argon",
    "number": 18,
    "mass": "39.948",
    "description": "Argon is element number 18 with atomic mass 39.948.",
    "category": "Noble Gas",
    "appearance": "Argon appears in a characteristic physical form typical to noble gass.",
    "electronConfiguration": "[Ne] 3s\u00b2 3p\u2076",
    "discovery": "The discovery of Argon dates back to historical or modern scientific research.",
    "occurrence": "Argon is found in nature or synthesized in laboratories.",
    "uses": "Argon is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Ar] - 18 electrons"
  },
  "K": {
    "name": "Potassium",
    "number": 19,
    "mass": "39.098",
    "description": "Potassium is element number 19 with atomic mass 39.098.",
    "category": "Alkali Metal",
    "appearance": "Potassium appears in a characteristic physical form typical to alkali metals.",
    "electronConfiguration": "[Ar] 4s\u00b9",
    "discovery": "The discovery of Potassium dates back to historical or modern scientific research.",
    "occurrence": "Potassium is found in nature or synthesized in laboratories.",
    "uses": "Potassium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [K] - 19 electrons"
  },
  "Ca": {
    "name": "Calcium",
    "number": 20,
    "mass": "40.078",
    "description": "Calcium is element number 20 with atomic mass 40.078.",
    "category": "Alkaline Earth Metal",
    "appearance": "Calcium appears in a characteristic physical form typical to alkaline earth metals.",
    "electronConfiguration": "[Ar] 4s\u00b2",
    "discovery": "The discovery of Calcium dates back to historical or modern scientific research.",
    "occurrence": "Calcium is found in nature or synthesized in laboratories.",
    "uses": "Calcium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Ca] - 20 electrons"
  },
  "Sc": {
    "name": "Scandium",
    "number": 21,
    "mass": "44.956",
    "description": "Scandium is element number 21 with atomic mass 44.956.",
    "category": "Transition Metal",
    "appearance": "Scandium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Ar] 3d\u00b9 4s\u00b2",
    "discovery": "The discovery of Scandium dates back to historical or modern scientific research.",
    "occurrence": "Scandium is found in nature or synthesized in laboratories.",
    "uses": "Scandium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Sc] - 21 electrons"
  },
  "Ti": {
    "name": "Titanium",
    "number": 22,
    "mass": "47.867",
    "description": "Titanium is element number 22 with atomic mass 47.867.",
    "category": "Transition Metal",
    "appearance": "Titanium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Ar] 3d\u00b2 4s\u00b2",
    "discovery": "The discovery of Titanium dates back to historical or modern scientific research.",
    "occurrence": "Titanium is found in nature or synthesized in laboratories.",
    "uses": "Titanium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Ti] - 22 electrons"
  },
  "V": {
    "name": "Vanadium",
    "number": 23,
    "mass": "50.942",
    "description": "Vanadium is element number 23 with atomic mass 50.942.",
    "category": "Transition Metal",
    "appearance": "Vanadium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Ar] 3d\u00b3 4s\u00b2",
    "discovery": "The discovery of Vanadium dates back to historical or modern scientific research.",
    "occurrence": "Vanadium is found in nature or synthesized in laboratories.",
    "uses": "Vanadium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [V] - 23 electrons"
  },
  "Cr": {
    "name": "Chromium",
    "number": 24,
    "mass": "51.996",
    "description": "Chromium is element number 24 with atomic mass 51.996.",
    "category": "Transition Metal",
    "appearance": "Chromium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Ar] 3d\u2075 4s\u00b9",
    "discovery": "The discovery of Chromium dates back to historical or modern scientific research.",
    "occurrence": "Chromium is found in nature or synthesized in laboratories.",
    "uses": "Chromium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Cr] - 24 electrons"
  },
  "Mn": {
    "name": "Manganese",
    "number": 25,
    "mass": "54.938",
    "description": "Manganese is element number 25 with atomic mass 54.938.",
    "category": "Transition Metal",
    "appearance": "Manganese appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Ar] 3d\u2075 4s\u00b2",
    "discovery": "The discovery of Manganese dates back to historical or modern scientific research.",
    "occurrence": "Manganese is found in nature or synthesized in laboratories.",
    "uses": "Manganese is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Mn] - 25 electrons"
  },
  "Fe": {
    "name": "Iron",
    "number": 26,
    "mass": "55.845",
    "description": "Iron is element number 26 with atomic mass 55.845.",
    "category": "Transition Metal",
    "appearance": "Silvery-gray metal",
    "electronConfiguration": "[Ar] 3d\u2076 4s\u00b2",
    "discovery": "Known since antiquity",
    "occurrence": "Earth's crust, ores like hematite",
    "uses": "Steel manufacturing, magnets, tools",
    "model": "Atomic Model: [Fe] - 26 electrons"
  },
  "Co": {
    "name": "Cobalt",
    "number": 27,
    "mass": "58.933",
    "description": "Cobalt is element number 27 with atomic mass 58.933.",
    "category": "Transition Metal",
    "appearance": "Cobalt appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Ar] 3d\u2077 4s\u00b2",
    "discovery": "The discovery of Cobalt dates back to historical or modern scientific research.",
    "occurrence": "Cobalt is found in nature or synthesized in laboratories.",
    "uses": "Cobalt is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Co] - 27 electrons"
  },
  "Ni": {
    "name": "Nickel",
    "number": 28,
    "mass": "58.693",
    "description": "Nickel is element number 28 with atomic mass 58.693.",
    "category": "Transition Metal",
    "appearance": "Nickel appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Ar] 3d\u2078 4s\u00b2",
    "discovery": "The discovery of Nickel dates back to historical or modern scientific research.",
    "occurrence": "Nickel is found in nature or synthesized in laboratories.",
    "uses": "Nickel is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Ni] - 28 electrons"
  },
  "Cu": {
    "name": "Copper",
    "number": 29,
    "mass": "63.546",
    "description": "Copper is element number 29 with atomic mass 63.546.",
    "category": "Transition Metal",
    "appearance": "Reddish-orange metal",
    "electronConfiguration": "[Ar] 3d\u00b9\u2070 4s\u00b9",
    "discovery": "Prehistoric times",
    "occurrence": "Copper ores, Earth's crust",
    "uses": "Wires, coins, plumbing, electronics",
    "model": "Atomic Model: [Cu] - 29 electrons"
  },
  "Zn": {
    "name": "Zinc",
    "number": 30,
    "mass": "65.38",
    "description": "Zinc is element number 30 with atomic mass 65.38.",
    "category": "Transition Metal",
    "appearance": "Zinc appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Ar] 3d\u00b9\u2070 4s\u00b2",
    "discovery": "The discovery of Zinc dates back to historical or modern scientific research.",
    "occurrence": "Zinc is found in nature or synthesized in laboratories.",
    "uses": "Zinc is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Zn] - 30 electrons"
  },
  "Ga": {
    "name": "Gallium",
    "number": 31,
    "mass": "69.723",
    "description": "Gallium is element number 31 with atomic mass 69.723.",
    "category": "Post-Transition Metal",
    "appearance": "Gallium appears in a characteristic physical form typical to post-transition metals.",
    "electronConfiguration": "[Ar] 3d\u00b9\u2070 4s\u00b2 4p\u00b9",
    "discovery": "The discovery of Gallium dates back to historical or modern scientific research.",
    "occurrence": "Gallium is found in nature or synthesized in laboratories.",
    "uses": "Gallium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Ga] - 31 electrons"
  },
  "Ge": {
    "name": "Germanium",
    "number": 32,
    "mass": "72.630",
    "description": "Germanium is element number 32 with atomic mass 72.630.",
    "category": "Metalloid",
    "appearance": "Germanium appears in a characteristic physical form typical to metalloids.",
    "electronConfiguration": "[Ar] 3d\u00b9\u2070 4s\u00b2 4p\u00b2",
    "discovery": "The discovery of Germanium dates back to historical or modern scientific research.",
    "occurrence": "Germanium is found in nature or synthesized in laboratories.",
    "uses": "Germanium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Ge] - 32 electrons"
  },
  "As": {
    "name": "Arsenic",
    "number": 33,
    "mass": "74.922",
    "description": "Arsenic is element number 33 with atomic mass 74.922.",
    "category": "Metalloid",
    "appearance": "Arsenic appears in a characteristic physical form typical to metalloids.",
    "electronConfiguration": "[Ar] 3d\u00b9\u2070 4s\u00b2 4p\u00b3",
    "discovery": "The discovery of Arsenic dates back to historical or modern scientific research.",
    "occurrence": "Arsenic is found in nature or synthesized in laboratories.",
    "uses": "Arsenic is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [As] - 33 electrons"
  },
  "Se": {
    "name": "Selenium",
    "number": 34,
    "mass": "78.971",
    "description": "Selenium is element number 34 with atomic mass 78.971.",
    "category": "Nonmetal",
    "appearance": "Selenium appears in a characteristic physical form typical to nonmetals.",
    "electronConfiguration": "[Ar] 3d\u00b9\u2070 4s\u00b2 4p\u2074",
    "discovery": "The discovery of Selenium dates back to historical or modern scientific research.",
    "occurrence": "Selenium is found in nature or synthesized in laboratories.",
    "uses": "Selenium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Se] - 34 electrons"
  },
  "Br": {
    "name": "Bromine",
    "number": 35,
    "mass": "79.904",
    "description": "Bromine is element number 35 with atomic mass 79.904.",
    "category": "Halogen",
    "appearance": "Bromine appears in a characteristic physical form typical to halogens.",
    "electronConfiguration": "[Ar] 3d\u00b9\u2070 4s\u00b2 4p\u2075",
    "discovery": "The discovery of Bromine dates back to historical or modern scientific research.",
    "occurrence": "Bromine is found in nature or synthesized in laboratories.",
    "uses": "Bromine is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Br] - 35 electrons"
  },
  "Kr": {
    "name": "Krypton",
    "number": 36,
    "mass": "83.798",
    "description": "Krypton is element number 36 with atomic mass 83.798.",
    "category": "Noble Gas",
    "appearance": "Krypton appears in a characteristic physical form typical to noble gass.",
    "electronConfiguration": "[Ar] 3d\u00b9\u2070 4s\u00b2 4p\u2076",
    "discovery": "The discovery of Krypton dates back to historical or modern scientific research.",
    "occurrence": "Krypton is found in nature or synthesized in laboratories.",
    "uses": "Krypton is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Kr] - 36 electrons"
  },
  "Rb": {
    "name": "Rubidium",
    "number": 37,
    "mass": "85.468",
    "description": "Rubidium is element number 37 with atomic mass 85.468.",
    "category": "Alkali Metal",
    "appearance": "Rubidium appears in a characteristic physical form typical to alkali metals.",
    "electronConfiguration": "[Kr] 5s\u00b9",
    "discovery": "The discovery of Rubidium dates back to historical or modern scientific research.",
    "occurrence": "Rubidium is found in nature or synthesized in laboratories.",
    "uses": "Rubidium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Rb] - 37 electrons"
  },
  "Sr": {
    "name": "Strontium",
    "number": 38,
    "mass": "87.62",
    "description": "Strontium is element number 38 with atomic mass 87.62.",
    "category": "Alkaline Earth Metal",
    "appearance": "Strontium appears in a characteristic physical form typical to alkaline earth metals.",
    "electronConfiguration": "[Kr] 5s\u00b2",
    "discovery": "The discovery of Strontium dates back to historical or modern scientific research.",
    "occurrence": "Strontium is found in nature or synthesized in laboratories.",
    "uses": "Strontium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Sr] - 38 electrons"
  },
  "Y": {
    "name": "Yttrium",
    "number": 39,
    "mass": "88.906",
    "description": "Yttrium is element number 39 with atomic mass 88.906.",
    "category": "Transition Metal",
    "appearance": "Yttrium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Kr] 4d\u00b9 5s\u00b2",
    "discovery": "The discovery of Yttrium dates back to historical or modern scientific research.",
    "occurrence": "Yttrium is found in nature or synthesized in laboratories.",
    "uses": "Yttrium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Y] - 39 electrons"
  },
  "Zr": {
    "name": "Zirconium",
    "number": 40,
    "mass": "91.224",
    "description": "Zirconium is element number 40 with atomic mass 91.224.",
    "category": "Transition Metal",
    "appearance": "Zirconium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Kr] 4d\u00b2 5s\u00b2",
    "discovery": "The discovery of Zirconium dates back to historical or modern scientific research.",
    "occurrence": "Zirconium is found in nature or synthesized in laboratories.",
    "uses": "Zirconium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Zr] - 40 electrons"
  },
  "Nb": {
    "name": "Niobium",
    "number": 41,
    "mass": "92.906",
    "description": "Niobium is element number 41 with atomic mass 92.906.",
    "category": "Transition Metal",
    "appearance": "Niobium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Kr] 4d\u2074 5s\u00b9",
    "discovery": "The discovery of Niobium dates back to historical or modern scientific research.",
    "occurrence": "Niobium is found in nature or synthesized in laboratories.",
    "uses": "Niobium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Nb] - 41 electrons"
  },
  "Mo": {
    "name": "Molybdenum",
    "number": 42,
    "mass": "95.95",
    "description": "Molybdenum is element number 42 with atomic mass 95.95.",
    "category": "Transition Metal",
    "appearance": "Molybdenum appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Kr] 4d\u2075 5s\u00b9",
    "discovery": "The discovery of Molybdenum dates back to historical or modern scientific research.",
    "occurrence": "Molybdenum is found in nature or synthesized in laboratories.",
    "uses": "Molybdenum is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Mo] - 42 electrons"
  },
  "Tc": {
    "name": "Technetium",
    "number": 43,
    "mass": "98",
    "description": "Technetium is element number 43 with atomic mass 98.",
    "category": "Transition Metal",
    "appearance": "Technetium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Kr] 4d\u2075 5s\u00b2",
    "discovery": "The discovery of Technetium dates back to historical or modern scientific research.",
    "occurrence": "Technetium is found in nature or synthesized in laboratories.",
    "uses": "Technetium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Tc] - 43 electrons"
  },
  "Ru": {
    "name": "Ruthenium",
    "number": 44,
    "mass": "101.07",
    "description": "Ruthenium is element number 44 with atomic mass 101.07.",
    "category": "Transition Metal",
    "appearance": "Ruthenium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Kr] 4d\u2077 5s\u00b9",
    "discovery": "The discovery of Ruthenium dates back to historical or modern scientific research.",
    "occurrence": "Ruthenium is found in nature or synthesized in laboratories.",
    "uses": "Ruthenium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Ru] - 44 electrons"
  },
  "Rh": {
    "name": "Rhodium",
    "number": 45,
    "mass": "102.91",
    "description": "Rhodium is element number 45 with atomic mass 102.91.",
    "category": "Transition Metal",
    "appearance": "Rhodium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Kr] 4d\u2078 5s\u00b9",
    "discovery": "The discovery of Rhodium dates back to historical or modern scientific research.",
    "occurrence": "Rhodium is found in nature or synthesized in laboratories.",
    "uses": "Rhodium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Rh] - 45 electrons"
  },
  "Pd": {
    "name": "Palladium",
    "number": 46,
    "mass": "106.42",
    "description": "Palladium is element number 46 with atomic mass 106.42.",
    "category": "Transition Metal",
    "appearance": "Palladium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Kr] 4d\u00b9\u2070",
    "discovery": "The discovery of Palladium dates back to historical or modern scientific research.",
    "occurrence": "Palladium is found in nature or synthesized in laboratories.",
    "uses": "Palladium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Pd] - 46 electrons"
  },
  "Ag": {
    "name": "Silver",
    "number": 47,
    "mass": "107.87",
    "description": "Silver is element number 47 with atomic mass 107.87.",
    "category": "Transition Metal",
    "appearance": "Silver appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Kr] 4d\u00b9\u2070 5s\u00b9",
    "discovery": "The discovery of Silver dates back to historical or modern scientific research.",
    "occurrence": "Silver is found in nature or synthesized in laboratories.",
    "uses": "Silver is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Ag] - 47 electrons"
  },
  "Cd": {
    "name": "Cadmium",
    "number": 48,
    "mass": "112.41",
    "description": "Cadmium is element number 48 with atomic mass 112.41.",
    "category": "Transition Metal",
    "appearance": "Cadmium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Kr] 4d\u00b9\u2070 5s\u00b2",
    "discovery": "The discovery of Cadmium dates back to historical or modern scientific research.",
    "occurrence": "Cadmium is found in nature or synthesized in laboratories.",
    "uses": "Cadmium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Cd] - 48 electrons"
  },
  "In": {
    "name": "Indium",
    "number": 49,
    "mass": "114.82",
    "description": "Indium is element number 49 with atomic mass 114.82.",
    "category": "Post-Transition Metal",
    "appearance": "Indium appears in a characteristic physical form typical to post-transition metals.",
    "electronConfiguration": "[Kr] 4d\u00b9\u2070 5s\u00b2 5p\u00b9",
    "discovery": "The discovery of Indium dates back to historical or modern scientific research.",
    "occurrence": "Indium is found in nature or synthesized in laboratories.",
    "uses": "Indium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [In] - 49 electrons"
  },
  "Sn": {
    "name": "Tin",
    "number": 50,
    "mass": "118.71",
    "description": "Tin is element number 50 with atomic mass 118.71.",
    "category": "Post-Transition Metal",
    "appearance": "Tin appears in a characteristic physical form typical to post-transition metals.",
    "electronConfiguration": "[Kr] 4d\u00b9\u2070 5s\u00b2 5p\u00b2",
    "discovery": "The discovery of Tin dates back to historical or modern scientific research.",
    "occurrence": "Tin is found in nature or synthesized in laboratories.",
    "uses": "Tin is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Sn] - 50 electrons"
  },
  "Sb": {
    "name": "Antimony",
    "number": 51,
    "mass": "121.76",
    "description": "Antimony is element number 51 with atomic mass 121.76.",
    "category": "Metalloid",
    "appearance": "Antimony appears in a characteristic physical form typical to metalloids.",
    "electronConfiguration": "[Kr] 4d\u00b9\u2070 5s\u00b2 5p\u00b3",
    "discovery": "The discovery of Antimony dates back to historical or modern scientific research.",
    "occurrence": "Antimony is found in nature or synthesized in laboratories.",
    "uses": "Antimony is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Sb] - 51 electrons"
  },
  "Te": {
    "name": "Tellurium",
    "number": 52,
    "mass": "127.60",
    "description": "Tellurium is element number 52 with atomic mass 127.60.",
    "category": "Metalloid",
    "appearance": "Tellurium appears in a characteristic physical form typical to metalloids.",
    "electronConfiguration": "[Kr] 4d\u00b9\u2070 5s\u00b2 5p\u2074",
    "discovery": "The discovery of Tellurium dates back to historical or modern scientific research.",
    "occurrence": "Tellurium is found in nature or synthesized in laboratories.",
    "uses": "Tellurium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Te] - 52 electrons"
  },
  "I": {
    "name": "Iodine",
    "number": 53,
    "mass": "126.90",
    "description": "Iodine is element number 53 with atomic mass 126.90.",
    "category": "Halogen",
    "appearance": "Iodine appears in a characteristic physical form typical to halogens.",
    "electronConfiguration": "[Kr] 4d\u00b9\u2070 5s\u00b2 5p\u2075",
    "discovery": "The discovery of Iodine dates back to historical or modern scientific research.",
    "occurrence": "Iodine is found in nature or synthesized in laboratories.",
    "uses": "Iodine is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [I] - 53 electrons"
  },
  "Xe": {
    "name": "Xenon",
    "number": 54,
    "mass": "131.29",
    "description": "Xenon is element number 54 with atomic mass 131.29.",
    "category": "Noble Gas",
    "appearance": "Xenon appears in a characteristic physical form typical to noble gass.",
    "electronConfiguration": "[Kr] 4d\u00b9\u2070 5s\u00b2 5p\u2076",
    "discovery": "The discovery of Xenon dates back to historical or modern scientific research.",
    "occurrence": "Xenon is found in nature or synthesized in laboratories.",
    "uses": "Xenon is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Xe] - 54 electrons"
  },
  "Cs": {
    "name": "Cesium",
    "number": 55,
    "mass": "132.91",
    "description": "Cesium is element number 55 with atomic mass 132.91.",
    "category": "Alkali Metal",
    "appearance": "Cesium appears in a characteristic physical form typical to alkali metals.",
    "electronConfiguration": "[Xe] 6s\u00b9",
    "discovery": "The discovery of Cesium dates back to historical or modern scientific research.",
    "occurrence": "Cesium is found in nature or synthesized in laboratories.",
    "uses": "Cesium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Cs] - 55 electrons"
  },
  "Ba": {
    "name": "Barium",
    "number": 56,
    "mass": "137.33",
    "description": "Barium is element number 56 with atomic mass 137.33.",
    "category": "Alkaline Earth Metal",
    "appearance": "Barium appears in a characteristic physical form typical to alkaline earth metals.",
    "electronConfiguration": "[Xe] 6s\u00b2",
    "discovery": "The discovery of Barium dates back to historical or modern scientific research.",
    "occurrence": "Barium is found in nature or synthesized in laboratories.",
    "uses": "Barium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Ba] - 56 electrons"
  },
  "La": {
    "name": "Lanthanum",
    "number": 57,
    "mass": "138.91",
    "description": "Lanthanum is element number 57 with atomic mass 138.91.",
    "category": "Lanthanide",
    "appearance": "Lanthanum appears in a characteristic physical form typical to lanthanides.",
    "electronConfiguration": "[Xe] 5d\u00b9 6s\u00b2",
    "discovery": "The discovery of Lanthanum dates back to historical or modern scientific research.",
    "occurrence": "Lanthanum is found in nature or synthesized in laboratories.",
    "uses": "Lanthanum is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [La] - 57 electrons"
  },
  "Ce": {
    "name": "Cerium",
    "number": 58,
    "mass": "140.12",
    "description": "Cerium is element number 58 with atomic mass 140.12.",
    "category": "Lanthanide",
    "appearance": "Cerium appears in a characteristic physical form typical to lanthanides.",
    "electronConfiguration": "[Xe] 4f\u00b9 5d\u00b9 6s\u00b2",
    "discovery": "The discovery of Cerium dates back to historical or modern scientific research.",
    "occurrence": "Cerium is found in nature or synthesized in laboratories.",
    "uses": "Cerium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Ce] - 58 electrons"
  },
  "Pr": {
    "name": "Praseodymium",
    "number": 59,
    "mass": "140.91",
    "description": "Praseodymium is element number 59 with atomic mass 140.91.",
    "category": "Lanthanide",
    "appearance": "Praseodymium appears in a characteristic physical form typical to lanthanides.",
    "electronConfiguration": "[Xe] 4f\u00b3 6s\u00b2",
    "discovery": "The discovery of Praseodymium dates back to historical or modern scientific research.",
    "occurrence": "Praseodymium is found in nature or synthesized in laboratories.",
    "uses": "Praseodymium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Pr] - 59 electrons"
  },
  "Nd": {
    "name": "Neodymium",
    "number": 60,
    "mass": "144.24",
    "description": "Neodymium is element number 60 with atomic mass 144.24.",
    "category": "Lanthanide",
    "appearance": "Neodymium appears in a characteristic physical form typical to lanthanides.",
    "electronConfiguration": "[Xe] 4f\u2074 6s\u00b2",
    "discovery": "The discovery of Neodymium dates back to historical or modern scientific research.",
    "occurrence": "Neodymium is found in nature or synthesized in laboratories.",
    "uses": "Neodymium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Nd] - 60 electrons"
  },
  "Pm": {
    "name": "Promethium",
    "number": 61,
    "mass": "145",
    "description": "Promethium is element number 61 with atomic mass 145.",
    "category": "Lanthanide",
    "appearance": "Promethium appears in a characteristic physical form typical to lanthanides.",
    "electronConfiguration": "[Xe] 4f\u2075 6s\u00b2",
    "discovery": "The discovery of Promethium dates back to historical or modern scientific research.",
    "occurrence": "Promethium is found in nature or synthesized in laboratories.",
    "uses": "Promethium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Pm] - 61 electrons"
  },
  "Sm": {
    "name": "Samarium",
    "number": 62,
    "mass": "150.36",
    "description": "Samarium is element number 62 with atomic mass 150.36.",
    "category": "Lanthanide",
    "appearance": "Samarium appears in a characteristic physical form typical to lanthanides.",
    "electronConfiguration": "[Xe] 4f\u2076 6s\u00b2",
    "discovery": "The discovery of Samarium dates back to historical or modern scientific research.",
    "occurrence": "Samarium is found in nature or synthesized in laboratories.",
    "uses": "Samarium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Sm] - 62 electrons"
  },
  "Eu": {
    "name": "Europium",
    "number": 63,
    "mass": "151.96",
    "description": "Europium is element number 63 with atomic mass 151.96.",
    "category": "Lanthanide",
    "appearance": "Europium appears in a characteristic physical form typical to lanthanides.",
    "electronConfiguration": "[Xe] 4f\u2077 6s\u00b2",
    "discovery": "The discovery of Europium dates back to historical or modern scientific research.",
    "occurrence": "Europium is found in nature or synthesized in laboratories.",
    "uses": "Europium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Eu] - 63 electrons"
  },
  "Gd": {
    "name": "Gadolinium",
    "number": 64,
    "mass": "157.25",
    "description": "Gadolinium is element number 64 with atomic mass 157.25.",
    "category": "Lanthanide",
    "appearance": "Gadolinium appears in a characteristic physical form typical to lanthanides.",
    "electronConfiguration": "[Xe] 4f\u2077 5d\u00b9 6s\u00b2",
    "discovery": "The discovery of Gadolinium dates back to historical or modern scientific research.",
    "occurrence": "Gadolinium is found in nature or synthesized in laboratories.",
    "uses": "Gadolinium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Gd] - 64 electrons"
  },
  "Tb": {
    "name": "Terbium",
    "number": 65,
    "mass": "158.93",
    "description": "Terbium is element number 65 with atomic mass 158.93.",
    "category": "Lanthanide",
    "appearance": "Terbium appears in a characteristic physical form typical to lanthanides.",
    "electronConfiguration": "[Xe] 4f\u2079 6s\u00b2",
    "discovery": "The discovery of Terbium dates back to historical or modern scientific research.",
    "occurrence": "Terbium is found in nature or synthesized in laboratories.",
    "uses": "Terbium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Tb] - 65 electrons"
  },
  "Dy": {
    "name": "Dysprosium",
    "number": 66,
    "mass": "162.50",
    "description": "Dysprosium is element number 66 with atomic mass 162.50.",
    "category": "Lanthanide",
    "appearance": "Dysprosium appears in a characteristic physical form typical to lanthanides.",
    "electronConfiguration": "[Xe] 4f\u00b9\u2070 6s\u00b2",
    "discovery": "The discovery of Dysprosium dates back to historical or modern scientific research.",
    "occurrence": "Dysprosium is found in nature or synthesized in laboratories.",
    "uses": "Dysprosium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Dy] - 66 electrons"
  },
  "Ho": {
    "name": "Holmium",
    "number": 67,
    "mass": "164.93",
    "description": "Holmium is element number 67 with atomic mass 164.93.",
    "category": "Lanthanide",
    "appearance": "Holmium appears in a characteristic physical form typical to lanthanides.",
    "electronConfiguration": "[Xe] 4f\u00b9\u00b9 6s\u00b2",
    "discovery": "The discovery of Holmium dates back to historical or modern scientific research.",
    "occurrence": "Holmium is found in nature or synthesized in laboratories.",
    "uses": "Holmium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Ho] - 67 electrons"
  },
  "Er": {
    "name": "Erbium",
    "number": 68,
    "mass": "167.26",
    "description": "Erbium is element number 68 with atomic mass 167.26.",
    "category": "Lanthanide",
    "appearance": "Erbium appears in a characteristic physical form typical to lanthanides.",
    "electronConfiguration": "[Xe] 4f\u00b9\u00b2 6s\u00b2",
    "discovery": "The discovery of Erbium dates back to historical or modern scientific research.",
    "occurrence": "Erbium is found in nature or synthesized in laboratories.",
    "uses": "Erbium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Er] - 68 electrons"
  },
  "Tm": {
    "name": "Thulium",
    "number": 69,
    "mass": "168.93",
    "description": "Thulium is element number 69 with atomic mass 168.93.",
    "category": "Lanthanide",
    "appearance": "Thulium appears in a characteristic physical form typical to lanthanides.",
    "electronConfiguration": "[Xe] 4f\u00b9\u00b3 6s\u00b2",
    "discovery": "The discovery of Thulium dates back to historical or modern scientific research.",
    "occurrence": "Thulium is found in nature or synthesized in laboratories.",
    "uses": "Thulium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Tm] - 69 electrons"
  },
  "Yb": {
    "name": "Ytterbium",
    "number": 70,
    "mass": "173.05",
    "description": "Ytterbium is element number 70 with atomic mass 173.05.",
    "category": "Lanthanide",
    "appearance": "Ytterbium appears in a characteristic physical form typical to lanthanides.",
    "electronConfiguration": "[Xe] 4f\u00b9\u2074 6s\u00b2",
    "discovery": "The discovery of Ytterbium dates back to historical or modern scientific research.",
    "occurrence": "Ytterbium is found in nature or synthesized in laboratories.",
    "uses": "Ytterbium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Yb] - 70 electrons"
  },
  "Lu": {
    "name": "Lutetium",
    "number": 71,
    "mass": "174.97",
    "description": "Lutetium is element number 71 with atomic mass 174.97.",
    "category": "Lanthanide",
    "appearance": "Lutetium appears in a characteristic physical form typical to lanthanides.",
    "electronConfiguration": "[Xe] 4f\u00b9\u2074 5d\u00b9 6s\u00b2",
    "discovery": "The discovery of Lutetium dates back to historical or modern scientific research.",
    "occurrence": "Lutetium is found in nature or synthesized in laboratories.",
    "uses": "Lutetium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Lu] - 71 electrons"
  },
  "Hf": {
    "name": "Hafnium",
    "number": 72,
    "mass": "178.49",
    "description": "Hafnium is element number 72 with atomic mass 178.49.",
    "category": "Transition Metal",
    "appearance": "Hafnium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Xe] 4f\u00b9\u2074 5d\u00b2 6s\u00b2",
    "discovery": "The discovery of Hafnium dates back to historical or modern scientific research.",
    "occurrence": "Hafnium is found in nature or synthesized in laboratories.",
    "uses": "Hafnium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Hf] - 72 electrons"
  },
  "Ta": {
    "name": "Tantalum",
    "number": 73,
    "mass": "180.95",
    "description": "Tantalum is element number 73 with atomic mass 180.95.",
    "category": "Transition Metal",
    "appearance": "Tantalum appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Xe] 4f\u00b9\u2074 5d\u00b3 6s\u00b2",
    "discovery": "The discovery of Tantalum dates back to historical or modern scientific research.",
    "occurrence": "Tantalum is found in nature or synthesized in laboratories.",
    "uses": "Tantalum is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Ta] - 73 electrons"
  },
  "W": {
    "name": "Tungsten",
    "number": 74,
    "mass": "183.84",
    "description": "Tungsten is element number 74 with atomic mass 183.84.",
    "category": "Transition Metal",
    "appearance": "Tungsten appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Xe] 4f\u00b9\u2074 5d\u2074 6s\u00b2",
    "discovery": "The discovery of Tungsten dates back to historical or modern scientific research.",
    "occurrence": "Tungsten is found in nature or synthesized in laboratories.",
    "uses": "Tungsten is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [W] - 74 electrons"
  },
  "Re": {
    "name": "Rhenium",
    "number": 75,
    "mass": "186.21",
    "description": "Rhenium is element number 75 with atomic mass 186.21.",
    "category": "Transition Metal",
    "appearance": "Rhenium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Xe] 4f\u00b9\u2074 5d\u2075 6s\u00b2",
    "discovery": "The discovery of Rhenium dates back to historical or modern scientific research.",
    "occurrence": "Rhenium is found in nature or synthesized in laboratories.",
    "uses": "Rhenium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Re] - 75 electrons"
  },
  "Os": {
    "name": "Osmium",
    "number": 76,
    "mass": "190.23",
    "description": "Osmium is element number 76 with atomic mass 190.23.",
    "category": "Transition Metal",
    "appearance": "Osmium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Xe] 4f\u00b9\u2074 5d\u2076 6s\u00b2",
    "discovery": "The discovery of Osmium dates back to historical or modern scientific research.",
    "occurrence": "Osmium is found in nature or synthesized in laboratories.",
    "uses": "Osmium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Os] - 76 electrons"
  },
  "Ir": {
    "name": "Iridium",
    "number": 77,
    "mass": "192.22",
    "description": "Iridium is element number 77 with atomic mass 192.22.",
    "category": "Transition Metal",
    "appearance": "Iridium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Xe] 4f\u00b9\u2074 5d\u2077 6s\u00b2",
    "discovery": "The discovery of Iridium dates back to historical or modern scientific research.",
    "occurrence": "Iridium is found in nature or synthesized in laboratories.",
    "uses": "Iridium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Ir] - 77 electrons"
  },
  "Pt": {
    "name": "Platinum",
    "number": 78,
    "mass": "195.08",
    "description": "Platinum is element number 78 with atomic mass 195.08.",
    "category": "Transition Metal",
    "appearance": "Platinum appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Xe] 4f\u00b9\u2074 5d\u2079 6s\u00b9",
    "discovery": "The discovery of Platinum dates back to historical or modern scientific research.",
    "occurrence": "Platinum is found in nature or synthesized in laboratories.",
    "uses": "Platinum is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Pt] - 78 electrons"
  },
  "Au": {
    "name": "Gold",
    "number": 79,
    "mass": "196.97",
    "description": "Gold is element number 79 with atomic mass 196.97.",
    "category": "Transition Metal",
    "appearance": "Gold appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Xe] 4f\u00b9\u2074 5d\u00b9\u2070 6s\u00b9",
    "discovery": "The discovery of Gold dates back to historical or modern scientific research.",
    "occurrence": "Gold is found in nature or synthesized in laboratories.",
    "uses": "Gold is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Au] - 79 electrons"
  },
  "Hg": {
    "name": "Mercury",
    "number": 80,
    "mass": "200.59",
    "description": "Mercury is element number 80 with atomic mass 200.59.",
    "category": "Transition Metal",
    "appearance": "Mercury appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Xe] 4f\u00b9\u2074 5d\u00b9\u2070 6s\u00b2",
    "discovery": "The discovery of Mercury dates back to historical or modern scientific research.",
    "occurrence": "Mercury is found in nature or synthesized in laboratories.",
    "uses": "Mercury is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Hg] - 80 electrons"
  },
  "Tl": {
    "name": "Thallium",
    "number": 81,
    "mass": "204.38",
    "description": "Thallium is element number 81 with atomic mass 204.38.",
    "category": "Post-Transition Metal",
    "appearance": "Thallium appears in a characteristic physical form typical to post-transition metals.",
    "electronConfiguration": "[Xe] 4f\u00b9\u2074 5d\u00b9\u2070 6s\u00b2 6p\u00b9",
    "discovery": "The discovery of Thallium dates back to historical or modern scientific research.",
    "occurrence": "Thallium is found in nature or synthesized in laboratories.",
    "uses": "Thallium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Tl] - 81 electrons"
  },
  "Pb": {
    "name": "Lead",
    "number": 82,
    "mass": "207.2",
    "description": "Lead is element number 82 with atomic mass 207.2.",
    "category": "Post-Transition Metal",
    "appearance": "Lead appears in a characteristic physical form typical to post-transition metals.",
    "electronConfiguration": "[Xe] 4f\u00b9\u2074 5d\u00b9\u2070 6s\u00b2 6p\u00b2",
    "discovery": "The discovery of Lead dates back to historical or modern scientific research.",
    "occurrence": "Lead is found in nature or synthesized in laboratories.",
    "uses": "Lead is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Pb] - 82 electrons"
  },
  "Bi": {
    "name": "Bismuth",
    "number": 83,
    "mass": "208.98",
    "description": "Bismuth is element number 83 with atomic mass 208.98.",
    "category": "Post-Transition Metal",
    "appearance": "Bismuth appears in a characteristic physical form typical to post-transition metals.",
    "electronConfiguration": "[Xe] 4f\u00b9\u2074 5d\u00b9\u2070 6s\u00b2 6p\u00b3",
    "discovery": "The discovery of Bismuth dates back to historical or modern scientific research.",
    "occurrence": "Bismuth is found in nature or synthesized in laboratories.",
    "uses": "Bismuth is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Bi] - 83 electrons"
  },
  "Po": {
    "name": "Polonium",
    "number": 84,
    "mass": "209",
    "description": "Polonium is element number 84 with atomic mass 209.",
    "category": "Post-Transition Metal",
    "appearance": "Polonium appears in a characteristic physical form typical to post-transition metals.",
    "electronConfiguration": "[Xe] 4f\u00b9\u2074 5d\u00b9\u2070 6s\u00b2 6p\u2074",
    "discovery": "The discovery of Polonium dates back to historical or modern scientific research.",
    "occurrence": "Polonium is found in nature or synthesized in laboratories.",
    "uses": "Polonium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Po] - 84 electrons"
  },
  "At": {
    "name": "Astatine",
    "number": 85,
    "mass": "210",
    "description": "Astatine is element number 85 with atomic mass 210.",
    "category": "Metalloid",
    "appearance": "Astatine appears in a characteristic physical form typical to metalloids.",
    "electronConfiguration": "[Xe] 4f\u00b9\u2074 5d\u00b9\u2070 6s\u00b2 6p\u2075",
    "discovery": "The discovery of Astatine dates back to historical or modern scientific research.",
    "occurrence": "Astatine is found in nature or synthesized in laboratories.",
    "uses": "Astatine is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [At] - 85 electrons"
  },
  "Rn": {
    "name": "Radon",
    "number": 86,
    "mass": "222",
    "description": "Radon is element number 86 with atomic mass 222.",
    "category": "Noble Gas",
    "appearance": "Radon appears in a characteristic physical form typical to noble gass.",
    "electronConfiguration": "[Xe] 4f\u00b9\u2074 5d\u00b9\u2070 6s\u00b2 6p\u2076",
    "discovery": "The discovery of Radon dates back to historical or modern scientific research.",
    "occurrence": "Radon is found in nature or synthesized in laboratories.",
    "uses": "Radon is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Rn] - 86 electrons"
  },
  "Fr": {
    "name": "Francium",
    "number": 87,
    "mass": "223",
    "description": "Francium is element number 87 with atomic mass 223.",
    "category": "Alkali Metal",
    "appearance": "Francium appears in a characteristic physical form typical to alkali metals.",
    "electronConfiguration": "[Rn] 7s\u00b9",
    "discovery": "The discovery of Francium dates back to historical or modern scientific research.",
    "occurrence": "Francium is found in nature or synthesized in laboratories.",
    "uses": "Francium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Fr] - 87 electrons"
  },
  "Ra": {
    "name": "Radium",
    "number": 88,
    "mass": "226",
    "description": "Radium is element number 88 with atomic mass 226.",
    "category": "Alkaline Earth Metal",
    "appearance": "Radium appears in a characteristic physical form typical to alkaline earth metals.",
    "electronConfiguration": "[Rn] 7s\u00b2",
    "discovery": "The discovery of Radium dates back to historical or modern scientific research.",
    "occurrence": "Radium is found in nature or synthesized in laboratories.",
    "uses": "Radium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Ra] - 88 electrons"
  },
  "Ac": {
    "name": "Actinium",
    "number": 89,
    "mass": "227",
    "description": "Actinium is element number 89 with atomic mass 227.",
    "category": "Actinide",
    "appearance": "Actinium appears in a characteristic physical form typical to actinides.",
    "electronConfiguration": "[Rn] 6d\u00b9 7s\u00b2",
    "discovery": "The discovery of Actinium dates back to historical or modern scientific research.",
    "occurrence": "Actinium is found in nature or synthesized in laboratories.",
    "uses": "Actinium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Ac] - 89 electrons"
  },
  "Th": {
    "name": "Thorium",
    "number": 90,
    "mass": "232.04",
    "description": "Thorium is element number 90 with atomic mass 232.04.",
    "category": "Actinide",
    "appearance": "Thorium appears in a characteristic physical form typical to actinides.",
    "electronConfiguration": "[Rn] 6d\u00b2 7s\u00b2",
    "discovery": "The discovery of Thorium dates back to historical or modern scientific research.",
    "occurrence": "Thorium is found in nature or synthesized in laboratories.",
    "uses": "Thorium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Th] - 90 electrons"
  },
  "Pa": {
    "name": "Protactinium",
    "number": 91,
    "mass": "231.04",
    "description": "Protactinium is element number 91 with atomic mass 231.04.",
    "category": "Actinide",
    "appearance": "Protactinium appears in a characteristic physical form typical to actinides.",
    "electronConfiguration": "[Rn] 5f\u00b2 6d\u00b9 7s\u00b2",
    "discovery": "The discovery of Protactinium dates back to historical or modern scientific research.",
    "occurrence": "Protactinium is found in nature or synthesized in laboratories.",
    "uses": "Protactinium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Pa] - 91 electrons"
  },
  "U": {
    "name": "Uranium",
    "number": 92,
    "mass": "238.03",
    "description": "Uranium is element number 92 with atomic mass 238.03.",
    "category": "Actinide",
    "appearance": "Uranium appears in a characteristic physical form typical to actinides.",
    "electronConfiguration": "[Rn] 5f\u00b3 6d\u00b9 7s\u00b2",
    "discovery": "The discovery of Uranium dates back to historical or modern scientific research.",
    "occurrence": "Uranium is found in nature or synthesized in laboratories.",
    "uses": "Uranium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [U] - 92 electrons"
  },
  "Np": {
    "name": "Neptunium",
    "number": 93,
    "mass": "237",
    "description": "Neptunium is element number 93 with atomic mass 237.",
    "category": "Actinide",
    "appearance": "Neptunium appears in a characteristic physical form typical to actinides.",
    "electronConfiguration": "[Rn] 5f\u2074 6d\u00b9 7s\u00b2",
    "discovery": "The discovery of Neptunium dates back to historical or modern scientific research.",
    "occurrence": "Neptunium is found in nature or synthesized in laboratories.",
    "uses": "Neptunium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Np] - 93 electrons"
  },
  "Pu": {
    "name": "Plutonium",
    "number": 94,
    "mass": "244",
    "description": "Plutonium is element number 94 with atomic mass 244.",
    "category": "Actinide",
    "appearance": "Plutonium appears in a characteristic physical form typical to actinides.",
    "electronConfiguration": "[Rn] 5f\u2076 7s\u00b2",
    "discovery": "The discovery of Plutonium dates back to historical or modern scientific research.",
    "occurrence": "Plutonium is found in nature or synthesized in laboratories.",
    "uses": "Plutonium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Pu] - 94 electrons"
  },
  "Am": {
    "name": "Americium",
    "number": 95,
    "mass": "243",
    "description": "Americium is element number 95 with atomic mass 243.",
    "category": "Actinide",
    "appearance": "Americium appears in a characteristic physical form typical to actinides.",
    "electronConfiguration": "[Rn] 5f\u2077 7s\u00b2",
    "discovery": "The discovery of Americium dates back to historical or modern scientific research.",
    "occurrence": "Americium is found in nature or synthesized in laboratories.",
    "uses": "Americium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Am] - 95 electrons"
  },
  "Cm": {
    "name": "Curium",
    "number": 96,
    "mass": "247",
    "description": "Curium is element number 96 with atomic mass 247.",
    "category": "Actinide",
    "appearance": "Curium appears in a characteristic physical form typical to actinides.",
    "electronConfiguration": "[Rn] 5f\u2077 6d\u00b9 7s\u00b2",
    "discovery": "The discovery of Curium dates back to historical or modern scientific research.",
    "occurrence": "Curium is found in nature or synthesized in laboratories.",
    "uses": "Curium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Cm] - 96 electrons"
  },
  "Bk": {
    "name": "Berkelium",
    "number": 97,
    "mass": "247",
    "description": "Berkelium is element number 97 with atomic mass 247.",
    "category": "Actinide",
    "appearance": "Berkelium appears in a characteristic physical form typical to actinides.",
    "electronConfiguration": "[Rn] 5f\u2079 7s\u00b2",
    "discovery": "The discovery of Berkelium dates back to historical or modern scientific research.",
    "occurrence": "Berkelium is found in nature or synthesized in laboratories.",
    "uses": "Berkelium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Bk] - 97 electrons"
  },
  "Cf": {
    "name": "Californium",
    "number": 98,
    "mass": "251",
    "description": "Californium is element number 98 with atomic mass 251.",
    "category": "Actinide",
    "appearance": "Californium appears in a characteristic physical form typical to actinides.",
    "electronConfiguration": "[Rn] 5f\u00b9\u2070 7s\u00b2",
    "discovery": "The discovery of Californium dates back to historical or modern scientific research.",
    "occurrence": "Californium is found in nature or synthesized in laboratories.",
    "uses": "Californium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Cf] - 98 electrons"
  },
  "Es": {
    "name": "Einsteinium",
    "number": 99,
    "mass": "252",
    "description": "Einsteinium is element number 99 with atomic mass 252.",
    "category": "Actinide",
    "appearance": "Einsteinium appears in a characteristic physical form typical to actinides.",
    "electronConfiguration": "[Rn] 5f\u00b9\u00b9 7s\u00b2",
    "discovery": "The discovery of Einsteinium dates back to historical or modern scientific research.",
    "occurrence": "Einsteinium is found in nature or synthesized in laboratories.",
    "uses": "Einsteinium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Es] - 99 electrons"
  },
  "Fm": {
    "name": "Fermium",
    "number": 100,
    "mass": "257",
    "description": "Fermium is element number 100 with atomic mass 257.",
    "category": "Actinide",
    "appearance": "Fermium appears in a characteristic physical form typical to actinides.",
    "electronConfiguration": "[Rn] 5f\u00b9\u00b2 7s\u00b2",
    "discovery": "The discovery of Fermium dates back to historical or modern scientific research.",
    "occurrence": "Fermium is found in nature or synthesized in laboratories.",
    "uses": "Fermium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Fm] - 100 electrons"
  },
  "Md": {
    "name": "Mendelevium",
    "number": 101,
    "mass": "258",
    "description": "Mendelevium is element number 101 with atomic mass 258.",
    "category": "Actinide",
    "appearance": "Mendelevium appears in a characteristic physical form typical to actinides.",
    "electronConfiguration": "[Rn] 5f\u00b9\u00b3 7s\u00b2",
    "discovery": "The discovery of Mendelevium dates back to historical or modern scientific research.",
    "occurrence": "Mendelevium is found in nature or synthesized in laboratories.",
    "uses": "Mendelevium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Md] - 101 electrons"
  },
  "No": {
    "name": "Nobelium",
    "number": 102,
    "mass": "259",
    "description": "Nobelium is element number 102 with atomic mass 259.",
    "category": "Actinide",
    "appearance": "Nobelium appears in a characteristic physical form typical to actinides.",
    "electronConfiguration": "[Rn] 5f\u00b9\u2074 7s\u00b2",
    "discovery": "The discovery of Nobelium dates back to historical or modern scientific research.",
    "occurrence": "Nobelium is found in nature or synthesized in laboratories.",
    "uses": "Nobelium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [No] - 102 electrons"
  },
  "Lr": {
    "name": "Lawrencium",
    "number": 103,
    "mass": "266",
    "description": "Lawrencium is element number 103 with atomic mass 266.",
    "category": "Actinide",
    "appearance": "Lawrencium appears in a characteristic physical form typical to actinides.",
    "electronConfiguration": "[Rn] 5f\u00b9\u2074 7s\u00b2 7p\u00b9",
    "discovery": "The discovery of Lawrencium dates back to historical or modern scientific research.",
    "occurrence": "Lawrencium is found in nature or synthesized in laboratories.",
    "uses": "Lawrencium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Lr] - 103 electrons"
  },
  "Rf": {
    "name": "Rutherfordium",
    "number": 104,
    "mass": "267",
    "description": "Rutherfordium is element number 104 with atomic mass 267.",
    "category": "Transition Metal",
    "appearance": "Rutherfordium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Rn] 5f\u00b9\u2074 6d\u00b2 7s\u00b2",
    "discovery": "The discovery of Rutherfordium dates back to historical or modern scientific research.",
    "occurrence": "Rutherfordium is found in nature or synthesized in laboratories.",
    "uses": "Rutherfordium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Rf] - 104 electrons"
  },
  "Db": {
    "name": "Dubnium",
    "number": 105,
    "mass": "268",
    "description": "Dubnium is element number 105 with atomic mass 268.",
    "category": "Transition Metal",
    "appearance": "Dubnium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Rn] 5f\u00b9\u2074 6d\u00b3 7s\u00b2",
    "discovery": "The discovery of Dubnium dates back to historical or modern scientific research.",
    "occurrence": "Dubnium is found in nature or synthesized in laboratories.",
    "uses": "Dubnium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Db] - 105 electrons"
  },
  "Sg": {
    "name": "Seaborgium",
    "number": 106,
    "mass": "269",
    "description": "Seaborgium is element number 106 with atomic mass 269.",
    "category": "Transition Metal",
    "appearance": "Seaborgium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Rn] 5f\u00b9\u2074 6d\u2074 7s\u00b2",
    "discovery": "The discovery of Seaborgium dates back to historical or modern scientific research.",
    "occurrence": "Seaborgium is found in nature or synthesized in laboratories.",
    "uses": "Seaborgium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Sg] - 106 electrons"
  },
  "Bh": {
    "name": "Bohrium",
    "number": 107,
    "mass": "270",
    "description": "Bohrium is element number 107 with atomic mass 270.",
    "category": "Transition Metal",
    "appearance": "Bohrium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Rn] 5f\u00b9\u2074 6d\u2075 7s\u00b2",
    "discovery": "The discovery of Bohrium dates back to historical or modern scientific research.",
    "occurrence": "Bohrium is found in nature or synthesized in laboratories.",
    "uses": "Bohrium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Bh] - 107 electrons"
  },
  "Hs": {
    "name": "Hassium",
    "number": 108,
    "mass": "277",
    "description": "Hassium is element number 108 with atomic mass 277.",
    "category": "Transition Metal",
    "appearance": "Hassium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Rn] 5f\u00b9\u2074 6d\u2076 7s\u00b2",
    "discovery": "The discovery of Hassium dates back to historical or modern scientific research.",
    "occurrence": "Hassium is found in nature or synthesized in laboratories.",
    "uses": "Hassium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Hs] - 108 electrons"
  },
  "Mt": {
    "name": "Meitnerium",
    "number": 109,
    "mass": "278",
    "description": "Meitnerium is element number 109 with atomic mass 278.",
    "category": "Transition Metal",
    "appearance": "Meitnerium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Rn] 5f\u00b9\u2074 6d\u2077 7s\u00b2",
    "discovery": "The discovery of Meitnerium dates back to historical or modern scientific research.",
    "occurrence": "Meitnerium is found in nature or synthesized in laboratories.",
    "uses": "Meitnerium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Mt] - 109 electrons"
  },
  "Ds": {
    "name": "Darmstadtium",
    "number": 110,
    "mass": "281",
    "description": "Darmstadtium is element number 110 with atomic mass 281.",
    "category": "Transition Metal",
    "appearance": "Darmstadtium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Rn] 5f\u00b9\u2074 6d\u2078 7s\u00b2",
    "discovery": "The discovery of Darmstadtium dates back to historical or modern scientific research.",
    "occurrence": "Darmstadtium is found in nature or synthesized in laboratories.",
    "uses": "Darmstadtium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Ds] - 110 electrons"
  },
  "Rg": {
    "name": "Roentgenium",
    "number": 111,
    "mass": "282",
    "description": "Roentgenium is element number 111 with atomic mass 282.",
    "category": "Transition Metal",
    "appearance": "Roentgenium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Rn] 5f\u00b9\u2074 6d\u2079 7s\u00b2",
    "discovery": "The discovery of Roentgenium dates back to historical or modern scientific research.",
    "occurrence": "Roentgenium is found in nature or synthesized in laboratories.",
    "uses": "Roentgenium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Rg] - 111 electrons"
  },
  "Cn": {
    "name": "Copernicium",
    "number": 112,
    "mass": "285",
    "description": "Copernicium is element number 112 with atomic mass 285.",
    "category": "Transition Metal",
    "appearance": "Copernicium appears in a characteristic physical form typical to transition metals.",
    "electronConfiguration": "[Rn] 5f\u00b9\u2074 6d\u00b9\u2070 7s\u00b2",
    "discovery": "The discovery of Copernicium dates back to historical or modern scientific research.",
    "occurrence": "Copernicium is found in nature or synthesized in laboratories.",
    "uses": "Copernicium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Cn] - 112 electrons"
  },
  "Nh": {
    "name": "Nihonium",
    "number": 113,
    "mass": "286",
    "description": "Nihonium is element number 113 with atomic mass 286.",
    "category": "Post-Transition Metal",
    "appearance": "Nihonium appears in a characteristic physical form typical to post-transition metals.",
    "electronConfiguration": "[Rn] 5f\u00b9\u2074 6d\u00b9\u2070 7s\u00b2 7p\u00b9",
    "discovery": "The discovery of Nihonium dates back to historical or modern scientific research.",
    "occurrence": "Nihonium is found in nature or synthesized in laboratories.",
    "uses": "Nihonium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Nh] - 113 electrons"
  },
  "Fl": {
    "name": "Flerovium",
    "number": 114,
    "mass": "289",
    "description": "Flerovium is element number 114 with atomic mass 289.",
    "category": "Post-Transition Metal",
    "appearance": "Flerovium appears in a characteristic physical form typical to post-transition metals.",
    "electronConfiguration": "[Rn] 5f\u00b9\u2074 6d\u00b9\u2070 7s\u00b2 7p\u00b2",
    "discovery": "The discovery of Flerovium dates back to historical or modern scientific research.",
    "occurrence": "Flerovium is found in nature or synthesized in laboratories.",
    "uses": "Flerovium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Fl] - 114 electrons"
  },
  "Mc": {
    "name": "Moscovium",
    "number": 115,
    "mass": "290",
    "description": "Moscovium is element number 115 with atomic mass 290.",
    "category": "Post-Transition Metal",
    "appearance": "Moscovium appears in a characteristic physical form typical to post-transition metals.",
    "electronConfiguration": "[Rn] 5f\u00b9\u2074 6d\u00b9\u2070 7s\u00b2 7p\u00b3",
    "discovery": "The discovery of Moscovium dates back to historical or modern scientific research.",
    "occurrence": "Moscovium is found in nature or synthesized in laboratories.",
    "uses": "Moscovium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Mc] - 115 electrons"
  },
  "Lv": {
    "name": "Livermorium",
    "number": 116,
    "mass": "293",
    "description": "Livermorium is element number 116 with atomic mass 293.",
    "category": "Post-Transition Metal",
    "appearance": "Livermorium appears in a characteristic physical form typical to post-transition metals.",
    "electronConfiguration": "[Rn] 5f\u00b9\u2074 6d\u00b9\u2070 7s\u00b2 7p\u2074",
    "discovery": "The discovery of Livermorium dates back to historical or modern scientific research.",
    "occurrence": "Livermorium is found in nature or synthesized in laboratories.",
    "uses": "Livermorium is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Lv] - 116 electrons"
  },
  "Ts": {
    "name": "Tennessine",
    "number": 117,
    "mass": "294",
    "description": "Tennessine is element number 117 with atomic mass 294.",
    "category": "Halogen",
    "appearance": "Tennessine appears in a characteristic physical form typical to halogens.",
    "electronConfiguration": "[Rn] 5f\u00b9\u2074 6d\u00b9\u2070 7s\u00b2 7p\u2075",
    "discovery": "The discovery of Tennessine dates back to historical or modern scientific research.",
    "occurrence": "Tennessine is found in nature or synthesized in laboratories.",
    "uses": "Tennessine is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Ts] - 117 electrons"
  },
  "Og": {
    "name": "Oganesson",
    "number": 118,
    "mass": "294",
    "description": "Oganesson is element number 118 with atomic mass 294.",
    "category": "Noble Gas",
    "appearance": "Oganesson appears in a characteristic physical form typical to noble gass.",
    "electronConfiguration": "[Rn] 5f\u00b9\u2074 6d\u00b9\u2070 7s\u00b2 7p\u2076",
    "discovery": "The discovery of Oganesson dates back to historical or modern scientific research.",
    "occurrence": "Oganesson is found in nature or synthesized in laboratories.",
    "uses": "Oganesson is used in various industrial, scientific, and technological applications.",
    "model": "Atomic Model: [Og] - 118 electrons"
  }
};

export default elements;